version: '3.1'

services:

  psql:
    image: postgres
    network_mode: host
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    expose:
        - 5432
  mongo:
        image: mongo
        ports:
                - 27017:27017

